// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCGZlJrcUWTObH4Kd4ZC9uFFsrVWSupEE',
    appId: '1:584201267144:web:deb1ebfeb6e969e3a842fd',
    messagingSenderId: '584201267144',
    projectId: 'jobber-15aad',
    authDomain: 'jobber-15aad.firebaseapp.com',
    storageBucket: 'jobber-15aad.appspot.com',
    measurementId: 'G-VYMQMWQTDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2l5bgjRUs4Wmsp93ivCH61kGEgJVcyE',
    appId: '1:584201267144:android:e5a788fb35196be0a842fd',
    messagingSenderId: '584201267144',
    projectId: 'jobber-15aad',
    storageBucket: 'jobber-15aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0-ZROGQXWcOEXpoSQpC4dvHpk-TfHuE',
    appId: '1:584201267144:ios:760366325e3853a7a842fd',
    messagingSenderId: '584201267144',
    projectId: 'jobber-15aad',
    storageBucket: 'jobber-15aad.appspot.com',
    iosClientId: '584201267144-0hd3oei8glmplgrad4288cqdgvclnvjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hire',
  );
}
